### ISSUE TITLE
Strong induction is already part of StdLib

### ISSUE THREAD

**Issue by DmxLarchey** [hferee/UIML#1]
https://github.com/hferee/UIML/blob/fffd11232f674759415c3337be9c7bdab7d35b00/theories/general/strong_inductionT.v#L5

```
Require Import Arith.

Check (well_founded_induction_type lt_wf).
```

**Comment by hferee** [comment]
Thank you @DmxLarchey . This folder is rather old legacy code ; there is probably a lot more to clean up there!
