### ISSUE TITLE
In the demo, fail for IL if a modality is present.

### ISSUE THREAD

**Issue by hferee** [hferee/UIML#10]
Following #7

**Comment by hferee** [comment]
Please @samvang check that the error message suits you.
An issue is that the placeholder formula has modalities, and the default selected logic is IL, so the default example will fail.

**Comment by samvang** [comment]
Yes. But we could make the standard example formula (~q -> p) & (p -> r), for example.

**Comment by samvang** [comment]
The error message looks fine
