### ISSUE TITLE
Output in web for IL is less simplified than that for iSL

### ISSUE THREAD

**Issue by samvang** [hferee/UIML#35]
The "IL" options of the web calculator are not yet connected to the latest optimization. 
For example on the formula `(((p -> q) -> r) -> s) -> t`, the option IL: E(p) gives output
`((((((q → (r ∧ (s → (t ∧ r)))) ∧ (s → (t ∧ (q → (r ∧ t))))) → q) → (r ∧ (s → (t ∧ r)))) ∧ (s → (t ∧ ((((q → (r ∧ t)) ∧ t) → q) → (r ∧ t))))) → s) → t`
while the option iSL: E(p) gives
`((((((q → (r ∧ (s → t))) ∧ (s → t)) → q) → (r ∧ (s → t))) ∧ (s → t)) → s) → t`
The difference becomes more extreme for longer formulas.
The same problem occurs for A(p).

**Comment by hferee** [comment]
Done.
